export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/ForgeFoxInc/ForgeFox",
	GITHUB_DISCUSSIONS: "https://github.com/ForgeFoxInc/ForgeFox/discussions",
	DISCORD: "https://discord.gg/forgefox",
	REDDIT: "https://reddit.com/r/ForgeFox",
	X: "https://x.com/forgefox",
	LINKEDIN: "https://www.linkedin.com/company/forgefox",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/forgefox.bsky.social",
	YOUTUBE: "https://www.youtube.com/@ForgeFoxYT",
	DOCUMENTATION: "https://docs.forgefox.com",
	SLACK_DOCS: "https://docs.forgefox.com/forgefox-cloud/slack-integration",
	CAREERS: "https://careers.forgefox.com",
	ISSUES: "https://github.com/ForgeFoxInc/ForgeFox/issues",
	FEATURE_REQUESTS: "https://github.com/ForgeFoxInc/ForgeFox/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/ForgeFoxInc/ForgeFox/discussions",
	CHANGELOG: "https://github.com/ForgeFoxInc/ForgeFox/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/ForgeFoxInc/ForgeFox/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.forgefox.com/community",
	TUTORIALS: "https://docs.forgefox.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=ForgeFox.forgefox",
	SECURITY: "https://trust.forgefox.com",
	EVALS: "https://forgefox.com/evals",
	BLOG_SUBSTACK: "https://blog.forgefox.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@ForgeFoxYT/podcasts",
	FAQ: "https://forgefox.com/#faq",
	TESTIMONIALS: "https://forgefox.com/#testimonials",
	CLOUD_APP_LOGIN: "https://app.forgefox.com/sign-in",
	CLOUD_APP_SIGNUP: "https://app.forgefox.com/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.forgefox.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.forgefox.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.forgefox.com/checkout/team",
	SUPPORT: "mailto:support@BusinessEdgeAnalytics.com",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
